# Simple workflow for deploying static content to GitHub Pages
name: Deploy wxRuby3-MaterialDesignArtProvider Pages

on:
  push:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base GUI setup
        run: |
          tools/scripts/setup-ubuntu.sh

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'ruby'

      - name: Setup Ruby gems
        run: |
          bundle config set --local with documentation
          bundle install

      - name: Test wxRuby3
        run: |
          bundle exec wxruby -h
          bundle exec wxruby check

      - name: Generate wxRuby3-MaterialDesignArtProvider
        run: |
          bundle exec ruby tools/generate_doc.rb

      - name: Build wxRuby3 HTML docs
        run: |
          bundle exec yardoc

      - name: Upload doc archive
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: wxruby3-mdap-html-reference
          path: doc
          overwrite: true

      - name: Setup Pages
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload Yard output only
          path: doc

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Archive html references docs
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          tar \
          --dereference --hard-dereference \
          --directory "doc" \
          -czf "$RUNNER_TEMP/wxruby3-mdap-html-reference.tar.gz" \
          "."

      - name: Upload doc archive as release asset
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ runner.temp }}/wxruby3-mdap-html-reference.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
